const keys = {
  keyRows: [
    [
      { keyCode: 'Backquote', isControl: false, width: 0 },
      { keyCode: 'Digit1', isControl: false, width: 0 },
      { keyCode: 'Digit2', isControl: false, width: 0 },
      { keyCode: 'Digit3', isControl: false, width: 0 },
      { keyCode: 'Digit4', isControl: false, width: 0 },
      { keyCode: 'Digit5', isControl: false, width: 0 },
      { keyCode: 'Digit6', isControl: false, width: 0 },
      { keyCode: 'Digit7', isControl: false, width: 0 },
      { keyCode: 'Digit8', isControl: false, width: 0 },
      { keyCode: 'Digit9', isControl: false, width: 0 },
      { keyCode: 'Digit0', isControl: false, width: 0 },
      { keyCode: 'Minus', isControl: false, width: 0 },
      { keyCode: 'Equal', isControl: false, width: 0 },
      { keyCode: 'Backspace', isControl: true, width: 2 },
    ],
    [
      { keyCode: 'Tab', isControl: true, width: 1 },
      { keyCode: 'KeyQ', isControl: false, width: 0 },
      { keyCode: 'KeyW', isControl: false, width: 0 },
      { keyCode: 'KeyE', isControl: false, width: 0 },
      { keyCode: 'KeyR', isControl: false, width: 0 },
      { keyCode: 'KeyT', isControl: false, width: 0 },
      { keyCode: 'KeyY', isControl: false, width: 0 },
      { keyCode: 'KeyU', isControl: false, width: 0 },
      { keyCode: 'KeyI', isControl: false, width: 0 },
      { keyCode: 'KeyO', isControl: false, width: 0 },
      { keyCode: 'KeyP', isControl: false, width: 0 },
      { keyCode: 'BracketLeft', isControl: false, width: 0 },
      { keyCode: 'BracketRight', isControl: false, width: 0 },
      { keyCode: 'Backslash', isControl: false, width: 0 },
    ],
    [
      { keyCode: 'CapsLock', isControl: true, width: 2 },
      { keyCode: 'KeyA', isControl: false, width: 0 },
      { keyCode: 'KeyS', isControl: false, width: 0 },
      { keyCode: 'KeyD', isControl: false, width: 0 },
      { keyCode: 'KeyF', isControl: false, width: 0 },
      { keyCode: 'KeyG', isControl: false, width: 0 },
      { keyCode: 'KeyH', isControl: false, width: 0 },
      { keyCode: 'KeyJ', isControl: false, width: 0 },
      { keyCode: 'KeyK', isControl: false, width: 0 },
      { keyCode: 'KeyL', isControl: false, width: 0 },
      { keyCode: 'Semicolon', isControl: false, width: 0 },
      { keyCode: 'Quote', isControl: false, width: 0 },
      { keyCode: 'Enter', isControl: true, width: 2 },
    ],
    [
      { keyCode: 'ShiftLeft', isControl: true, width: 1 },
      { keyCode: 'KeyZ', isControl: false, width: 0 },
      { keyCode: 'KeyX', isControl: false, width: 0 },
      { keyCode: 'KeyC', isControl: false, width: 0 },
      { keyCode: 'KeyV', isControl: false, width: 0 },
      { keyCode: 'KeyB', isControl: false, width: 0 },
      { keyCode: 'KeyN', isControl: false, width: 0 },
      { keyCode: 'KeyM', isControl: false, width: 0 },
      { keyCode: 'Comma', isControl: false, width: 0 },
      { keyCode: 'Period', isControl: false, width: 0 },
      { keyCode: 'Slash', isControl: false, width: 0 },
      { keyCode: 'ArrowUp', isControl: true, width: 0 },
      { keyCode: 'ShiftRight', isControl: true, width: 1 },
    ],
    [
      { keyCode: 'ControlLeft', isControl: true, width: 0 },
      { keyCode: 'AltLeft', isControl: true, width: 0 },
      { keyCode: 'Space', isControl: false, width: 3 },
      { keyCode: 'AltRight', isControl: true, width: 0 },
      { keyCode: 'ControlRight', isControl: true, width: 0 },
      { keyCode: 'ArrowLeft', isControl: true, width: 0 },
      { keyCode: 'ArrowDown', isControl: true, width: 0 },
      { keyCode: 'ArrowRight', isControl: true, width: 0 },
    ],
  ],
  layoutMaps: {
    eng: {
      Backquote: { text: '`', shiftText: '~' },
      Digit1: { text: '1', shiftText: '!' },
      Digit2: { text: '2', shiftText: '@' },
      Digit3: { text: '3', shiftText: '#' },
      Digit4: { text: '4', shiftText: '$' },
      Digit5: { text: '5', shiftText: '%' },
      Digit6: { text: '6', shiftText: '^' },
      Digit7: { text: '7', shiftText: '&' },
      Digit8: { text: '8', shiftText: '*' },
      Digit9: { text: '9', shiftText: '(' },
      Digit0: { text: '0', shiftText: ')' },
      Minus: { text: '-', shiftText: '_' },
      Equal: { text: '=', shiftText: '+' },
      Backspace: { text: 'Backspace', shiftText: null },
      Tab: { text: 'Tab', shiftText: null },
      KeyQ: { text: 'q', shiftText: 'Q' },
      KeyW: { text: 'w', shiftText: 'W' },
      KeyE: { text: 'e', shiftText: 'E' },
      KeyR: { text: 'r', shiftText: 'R' },
      KeyT: { text: 't', shiftText: 'T' },
      KeyY: { text: 'y', shiftText: 'Y' },
      KeyU: { text: 'u', shiftText: 'U' },
      KeyI: { text: 'i', shiftText: 'I' },
      KeyO: { text: 'o', shiftText: 'O' },
      KeyP: { text: 'p', shiftText: 'P' },
      BracketLeft: { text: '[', shiftText: '{' },
      BracketRight: { text: ']', shiftText: '}' },
      Backslash: { text: '\\', shiftText: '|' },
      CapsLock: { text: 'CapsLock', shiftText: null },
      KeyA: { text: 'a', shiftText: 'A' },
      KeyS: { text: 's', shiftText: 'S' },
      KeyD: { text: 'd', shiftText: 'D' },
      KeyF: { text: 'f', shiftText: 'F' },
      KeyG: { text: 'g', shiftText: 'G' },
      KeyH: { text: 'h', shiftText: 'H' },
      KeyJ: { text: 'j', shiftText: 'J' },
      KeyK: { text: 'k', shiftText: 'K' },
      KeyL: { text: 'l', shiftText: 'L' },
      Semicolon: { text: ';', shiftText: ':' },
      Quote: { text: "'", shiftText: '"' },
      Enter: { text: 'Enter', shiftText: null },
      ShiftLeft: { text: 'Shift', shiftText: null },
      KeyZ: { text: 'z', shiftText: 'Z' },
      KeyX: { text: 'x', shiftText: 'X' },
      KeyC: { text: 'c', shiftText: 'C' },
      KeyV: { text: 'v', shiftText: 'V' },
      KeyB: { text: 'b', shiftText: 'B' },
      KeyN: { text: 'n', shiftText: 'N' },
      KeyM: { text: 'm', shiftText: 'M' },
      Comma: { text: ',', shiftText: '<' },
      Period: { text: '.', shiftText: '>' },
      Slash: { text: '/', shiftText: '?' },
      ArrowUp: { text: '↑', shiftText: null },
      ShiftRight: { text: 'Shift', shiftText: null },
      ControlLeft: { text: 'Ctrl', shiftText: null },
      AltLeft: { text: 'Alt', shiftText: null },
      Space: { text: ' ', shiftText: ' ' },
      AltRight: { text: 'Alt', shiftText: null },
      ControlRight: { text: 'Ctrl', shiftText: null },
      ArrowLeft: { text: '←', shiftText: null },
      ArrowDown: { text: '↓', shiftText: null },
      ArrowRight: { text: '→', shiftText: null },
    },
  },
};
export { keys as default };
